### ISSUE TITLE
AddSbomTool() forces use of Serilog

### ISSUE THREAD

**Issue by micyunmsft** [microsoft/sbom-tool#477] opened 2024-01-10 22:41 UTC
To use sbom-tool from our Azure function, we call AddSbomTool in our DI code. However, AddSbomTool calls a [ConfigureLoggingProviders](https://github.com/microsoft/sbom-tool/blob/d251a5f7967dd890fb42013a2476e07f461e3a3c/src/Microsoft.Sbom.Extensions.DependencyInjection/ServiceCollectionExtensions.cs#L224) method that basically forces us to use Serilog. This is changing the format of our function's logs. I have attached an example of what our function's logs look like before and after calling AddSbomTool.

It would be ideal if the logging providers code was separated out so that we don't have to call it when invoking AddSbomTool. Our code should be in charge of defining the logging for our function, not sbom-tool.

Note that we also tried to mitigate this by clearing logging providers after registering sbom-tool, but nothing changed.

`services.AddLogging(l => l.ClearProviders()`

[query_data 1.csv](https://github.com/microsoft/sbom-tool/files/13895266/query_data.1.csv)

**Comment by jalkire** [comment] 2024-02-29 23:58
Closing as duplicate of #284

**Closed by jalkire** 2024-02-29 23:58 UTC
Labels: accepted
