### ISSUE TITLE
unexpected input argument will prompt --help but exit_code still be 0

### ISSUE THREAD

**Issue by zongtaol** [microsoft/sbom-tool#520] opened 2024-03-05 21:51 UTC
I am using run_subprocess function in python to invoke sbom-tool generate command. which given invalid input, it will prompt --help function, but exit_code is 0, which run_subprocess believe this command is executed successfully and continue to the next step.

Is there a way to tell the command got unexpected input and throw an exception instead of an exit_code = 0 return?
![Screenshot 2024-03-05 134828](https://github.com/microsoft/sbom-tool/assets/91494184/3a01b808-2d62-49dc-a447-29e5add3bffe)

**Comment by pownkel** [comment] 2024-03-06 01:23
For some reason I can't reproduce the issue on powershell unless I'm using Python's subprocess.run() method, but it seems to happen consistently on cmd. It looks like the issue is that we [don't explicitly set the exit code](https://github.com/microsoft/sbom-tool/blob/main/src/Microsoft.Sbom.Tool/Program.cs#L40) if the tool encounters an argument parsing error.

**Comment by DaveTryon** [comment] 2024-04-10 17:51
Fix has been merged and will be included in our next release

**Closed by DaveTryon** 2024-04-10 17:51 UTC
Labels: accepted
