### ISSUE TITLE
Use proper path seperator for directories

### ISSUE THREAD

**Issue by aasim** [microsoft/sbom-tool#240] opened 2023-04-17 21:01 UTC
This commit was reverted due to some failures, we need to rework it, test and deploy to make sure that all path separators work as excpected.

https://github.com/microsoft/sbom-tool/pull/208/files

Revert: https://github.com/microsoft/sbom-tool/commit/82b1e774785fc128e88a3954969338645a07d526

This is causing customer failures. ex. https://dev.azure.com/powerbi/Insights%20Apps%20Platform/_build/results?buildId=6800014&view=logs&j=f879d28a-4410-5cef-60af-287ec2db150b&t=b8eb8a70-003a-5bc5-3d51-3963fcdfd045&l=18

**Comment by edgarrs** [comment] 2023-04-24 19:21
Duplicate of #194

**Closed** 2023-06-15 13:55 UTC
Labels: bug, aa-triaged
